# Generated by Django 4.2 on 2023-04-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttrInfo",
            fields=[
                ("i_id", models.AutoField(primary_key=True, serialize=False)),
                ("attraction", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RestInfo",
            fields=[
                ("i_id", models.AutoField(primary_key=True, serialize=False)),
                ("restaurant", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("u_id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=50)),
            ],
        ),
    ]
