# Generated by Django 4.2 on 2023-05-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ursapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attrinfo",
            old_name="location",
            new_name="url",
        ),
        migrations.RenameField(
            model_name="restinfo",
            old_name="location",
            new_name="url",
        ),
        migrations.AddField(
            model_name="attrinfo",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="attrinfo",
            name="rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="attrinfo",
            name="tags",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="restinfo",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="restinfo",
            name="rating",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="restinfo",
            name="tags",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
