# Generated by Django 4.2.1 on 2023-05-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ursapp", "0002_attrinfo_restinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewAttrInfo",
            fields=[
                ("r_id", models.AutoField(primary_key=True, serialize=False)),
                ("u_id", models.IntegerField(null=True)),
                ("p_id", models.IntegerField(null=True)),
                ("rating", models.IntegerField(null=True)),
                ("review", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewRestInfo",
            fields=[
                ("r_id", models.AutoField(primary_key=True, serialize=False)),
                ("u_id", models.IntegerField(null=True)),
                ("p_id", models.IntegerField(null=True)),
                ("rating", models.IntegerField(null=True)),
                ("review", models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
