# Generated by Django 4.2 on 2023-05-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ursapp", "0003_reviewattrinfo_reviewrestinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAttrReview",
            fields=[
                ("r_id", models.IntegerField(primary_key=True, serialize=False)),
                ("u_id", models.IntegerField(null=True)),
                ("p_id", models.IntegerField(null=True)),
                ("rating", models.IntegerField(null=True)),
                ("review", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="UserRestReview",
            fields=[
                ("r_id", models.IntegerField(primary_key=True, serialize=False)),
                ("u_id", models.IntegerField(null=True)),
                ("p_id", models.IntegerField(null=True)),
                ("rating", models.IntegerField(null=True)),
                ("review", models.CharField(max_length=500)),
            ],
        ),
    ]
