# Generated by Django 4.1.7 on 2023-05-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ursapp', '0004_userattrreview_userrestreview'),
    ]

    operations = [
    ]
