# Generated by Django 4.1.7 on 2023-05-27 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ursapp", "0005_rename_r_id_userattrreview_pr_id_and_more"),
    ]

    operations = [
    ]
