# Generated by Django 4.2.1 on 2023-05-30 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ursapp", "0006_rename_r_id_userattrreview_pr_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userattrreview",
            old_name="r_id",
            new_name="pr_id",
        ),
        migrations.RenameField(
            model_name="userrestreview",
            old_name="r_id",
            new_name="pr_id",
        ),
        migrations.RemoveField(
            model_name="userattrreview",
            name="u_id",
        ),
        migrations.RemoveField(
            model_name="userrestreview",
            name="u_id",
        ),
    ]
